server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/

spring:
  application:
    name: spring-cloud-feign-client

feign:
  hystrix:
    enabled: true
