#应用端口，Eureka服务端默认为：8761
server:
  port: 9999

#通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
eureka:
  instance:
    # 应用实例主机名
    hostname: localhost
  client:
    # 是否向注册中心注册自己，缺省：true
    register-with-eureka: false
    # 是否从Eureka获取注册信息，缺省：true
    # 一般情况下，Eureka服务端是不需要的
    fetch-registry: false
    # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:8761/eureka
    # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://127.0.0.1:9999/eureka/,http://127.0.0.1:9998/eureka/

#应用名称，将会显示在Eureka界面的应用名称列
spring:
  application:
    name: spring-cloud-eureka
