server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: after_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://127.0.0.1:8764/getInfo
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: after_route
