server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
      #当eureka为集群时，不代表当前客户端需要在Eureka Server注册三次，这里只需要注册一次就可以了，但是为什么要写三个地址，只要有一台服务还建在，那么就可以注册服务。
      #defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          #服务的git仓库地址
          uri: https://github.com/LLBlood/spring-cloud-integration-config-repo
          #配置文件所在的目录
          search-paths: /**
      #配置文件所在的分支
      label: master
      #git仓库的用户名
      username:
      #git仓库的密码
      password:
